import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import TanStackProvider from "./providers/TanStackProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Super Shop",
//   description: "Generated by create Super Shop",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`bg-[#010313] ${inter.className}`}>
        <TanStackProvider>
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
